# Generated by Django 4.2.5 on 2023-09-27 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('birth_date', models.DateField()),
                ('phone_number', models.PositiveIntegerField()),
                ('housing_type', models.CharField(choices=[('Casa Propia', 'Casa Propia'), ('Casa en renta', 'Casa en renta')], default='Casa Propia', max_length=50)),
                ('health_service', models.CharField(choices=[('S.O.S', 'SOS'), ('Sura', 'Sura')], default='S.O.S', max_length=50)),
                ('family_education_level', models.CharField(choices=[('Basica', 'Basica'), ('Media', 'Media'), ('Superior', 'Superior')], default='Basica', max_length=50)),
                ('work_situation', models.CharField(choices=[('Empleado', 'Empleado'), ('Desempleado', 'Desempleado'), ('Comerciante', 'Comerciante')], default='Empleado', max_length=50)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0)),
                ('frecuency_attendance', models.CharField(choices=[('Alto', 'Alto'), ('Medio', 'Medio'), ('Bajo', 'Bajo')], default='Alto', max_length=50)),
                ('missing_classes', models.CharField(max_length=50)),
                ('related_activities_at_school', models.CharField(max_length=50)),
                ('study_group', models.CharField(max_length=50)),
                ('support_service', models.CharField(max_length=50)),
                ('hours_worked', models.PositiveIntegerField()),
                ('family_support', models.CharField(max_length=50)),
                ('stress_levels', models.CharField(max_length=50)),
                ('stress_source', models.CharField(max_length=50)),
                ('job_expectations', models.CharField(max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('phase', models.CharField(choices=[('Creado', 'Creado'), ('En Proceso', 'Medio'), ('Concluido', 'Concluido')], default='Creado', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.areas', verbose_name='Area')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('Creado', 'Creado'), ('En Proceso', 'Medio'), ('Concluido', 'Concluido')], default='En Proceso', max_length=100)),
                ('comments', models.TextField(blank=True, null=True)),
                ('evidence', models.TextField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tickets', verbose_name='Tickets')),
            ],
            options={
                'verbose_name': 'FollowUp',
                'verbose_name_plural': 'FollowUps',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('Creado', 'Creado'), ('En Proceso', 'Medio'), ('Concluido', 'Concluido')], default='Concluido', max_length=100)),
                ('comments', models.TextField()),
                ('qualification', models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('followUp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.followup', verbose_name='Follow Up')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
    ]
