# Generated by Django 4.2.5 on 2023-09-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_feedback_is_active_followup_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
