# Generated by Django 4.2.5 on 2023-09-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_student_birth_date_alter_student_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='average',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='family_support',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='frecuency_attendance',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='hours_worked',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='job_expectations',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='missing_classes',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='related_activities_at_school',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='stress_levels',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='stress_source',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='study_group',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='support_service',
            field=models.CharField(max_length=50),
        ),
    ]
